Win and lose - print screens and corrects conditions
niemarcin/object-oriented-programming pull request #58
Opened 2020-08-03 20:00 UTC by niemarcin

closes #42 
closes #43

2020-08-04 11:19 UTC, J-Cieplinski requested changes

2020-08-04 11:19 UTC, PierwszyKrytykRP commented on shm/Game.hpp
> +    const size_t days_;
```suggestion
    const size_t campaignTime_;
```

2020-08-04 11:19 UTC, PierwszyKrytykRP commented on shm/Game.hpp
> +    const size_t days_;
Or similar. It shouldn't stays as `days_` since it's misleading

2020-08-05 08:15 UTC, J-Cieplinski requested changes

2020-08-05 08:15 UTC, PierwszyKrytykRP commented on shm/Game.cpp
> +Game::Game(size_t money, size_t days, size_t finalGoal)
```suggestion
Game::Game(size_t money, size_t timeLimit, size_t finalGoal)
```

2020-08-05 16:58 UTC, J-Cieplinski approved these changes

2020-08-05 17:19 UTC, iprice73 approved these changes

2020-08-05 17:19 UTC, LogarithmDerivative commented on shm/Game.cpp
> +    int i = 0;
Does this line have a purpose, I do not see any use of it later in code

2020-08-05 17:19 UTC, LogarithmDerivative commented on shm/Game.cpp
> +    int i = 0;
same here

2020-08-05 17:19 UTC, LogarithmDerivative commented on shm/Game.cpp
> +    int i = 0;
and here

2020-08-05 17:24 UTC, merged